seed: 86
esass_image: DR1

files:
  obs_path: '../data/LMC_SN1987A/'
  data_dict: 'data.pkl'
  processed_obs_folder: 'processed'  # only needed for actual data
  input: 'pm00_700161_020_EventList_c001.fits'
  output: 'pm00_700161_020_data.fits'
  exposure: 'pm00_700161_020_expmap.fits'
  calibration_path : '../data/'
  caldb_folder_name: 'caldb'
  psf_filename_suffix: '_2dpsf_190219v05.fits'
  effective_area_filename_suffix: '_arf_filter_000101v02.fits'
  res_dir: 'results/Mock-17092024-001M'
  prior_plot_dir: 'prior_samples'
  # If mock:
  mock_gen_config: 'configs/eROSITA_demo.yaml' # only needed for mock
  pos_dict: 'pos.pkl' # only needed for mock

telescope:
  tm_ids : [1, 2, 3, 4, 6]
  pointing_center: [83.77602098929445, -69.31087419596945]
  rebin: 80 # typical value used in analysis; equals 4 arcsec resolution
  fov: 4096
  pattern: 15
  detmap: True
  exp_cut: 500
  badpix_correction: True
  effective_area_correction: True

psf:
 energy: ['0277', '1486', '3000']
  # LIN config
 npatch: 8
 margfrac: 0.062
 want_cut: False

plotting:
  priors: False
  priors_signal_response: True
  n_prior_samples: 5
  enabled: True
  slice: Null
  dpi: 300

grid:
  sdim: 1024
  edim: 3 # FIXME: remove this parameter
  s_padding_ratio: 1.1075 # leads to a 1134, which is a "good size" padded space
  e_padding_ratio: 1.
  energy_bin:
    e_min:
    - 0.2
    e_max:
    - 1.0
    e_ref:
    - 0.6

priors:
  point_sources:
    spatial:
      alpha: 1.0052423392975538
      key: points
      q: 1.0899834483573917e-11
    # dev_wp:
    #  name: points_dev_wp
    #  sigma:
    #  - 0.01
    #  - 0.02
    #  x0: 0
    plaw:
      mean: -0.3
      name: points_plaw_
      std: 0.1

#    dev_corr:
#      fluctuations:
#        fluctuations:
#          - 1.0
#          - 5.0e-3
#        loglogavgslope:
#          - -3
#          - 1.0e-2
#        flexibility:
#          - 2.0
#          - 5.0e-1
#        asperity:
#        non_parametric_kind: "power"
#        # harmonic_type: "Fourier"
#      prefix: points_dev
#      offset:
#        offset_mean: 0.0
#        offset_std:
#          - 1.0e-3
#          - 1.0e-4
  diffuse:
    spatial:
      fluctuations:
        asperity: null
        flexibility:
        - 0.3
        - 0.01
        fluctuations:
        - 0.3
        - 0.01
        loglogavgslope:
        - -5.0
        - 0.1
        non_parametric_kind: power
      offset:
        offset_mean: -19.0
        offset_std:
        - 0.3
        - 0.05
      prefix: diffuse_spatial_
    plaw:
      fluctuations:
        asperity: null
        flexibility:
        - 0.01
        - 0.001
        fluctuations:
        - 0.01
        - 0.001
        loglogavgslope:
        - -6.0
        - 0.01
        non_parametric_kind: power
      offset:
        offset_mean: -1.3
        offset_std:
        - 0.01
        - 0.001
      prefix: diffuse_plaw_
minimization:
    resume: False
    n_total_iterations: 30
    delta:
      switches:
      values: 1.e-5

    samples:
      switches: [0, 10]
      n_samples: 4
      mode: [nonlinear_resample, nonlinear_resample]
      # Possible modes:
      # - "linear_sample",
      # - "linear_resample",
      # - "nonlinear_sample",
      # - "nonlinear_resample",
      # - "nonlinear_update",

      # LIN SAMPLING
      # lin_absdelta: [Null, 1.e-4] # if set, delta is ignored
      lin_maxiter: 100

      # NONLIN SAMPLING
      # nonlin_xtol: [Null, 0.1] # if set, delta is ignored
      nonlin_maxiter: 3
      # nonlin_cg_atol: [0.1, 0.01]
      # nonlin_cg_maxiter: [20, 30]

    kl_minimization:
      switches:
      # kl_absdelta: [Null, 1.e-6] # if set, delta is ignored
      kl_maxiter: 20
