output: 
  dir: 'results/mock_data'
  output_attach: 'test_01'

mock_setup:
  plot: False
  noise_scale: 0.08
  mock_distance: 0.05
  mock_shape: 1536 
  # mock_shape: 512 
  # mock_shape: 256
  rota_shape: 768 
  # rota_shape: 512
  reco_shape: 128
  data_shape: 48
  # data_shape: 32

  rotation: 'linear'

  # shifts: [[0, 0]]
  # reported_shifts: [[0, 0]]
  # rotations: [0]
  # reported_rotations: [0]

  # shifts: [[0, 0], [0, 0]]
  # reported_shifts: [[0, 0], [0, 0]]
  # rotations: [0, 45]
  # reported_rotations: [0, 45]

  shifts: [[0, 10], [0, 0]]
  reported_shifts: [[0, 8], [0, 0]]
  rotations: [2, 23]
  reported_rotations: [2, 23]

  sky_dict:
    offset: 
      offset_mean: 0.1
      offset_std: [0.1, 0.05]
    fluctuations: 
      fluctuations: [0.3, 0.03]
      loglogavgslope: [-3., 1.]
      flexibility: [0.8, 0.1]
      asperity: [0.2, 0.1]

sky_model:
  plot_sky_model: False
  extend_factor: 1.5
  offset: 
    offset_mean: 3.7
    offset_std: [0.1, 0.05]
  fluctuations: 
    fluctuations: [0.7, 0.03]
    loglogavgslope: [-4.8, 1.]
    flexibility: [0.8, 0.1]
    asperity: [0.2, 0.1]

telescope:
  rotation_and_shift:
    model: 'linear' # 'sparse', 'linear', 'nufft'
    subsample: 4
    order: 1
    # mean: [0, 0]
    # sigma: [0.1, 0.1]

minimization:
  resume: False
  n_total_iterations: 50
  n_samples: 4
  draw_linear_kwargs:
    cg_name : "lin sampling"
    cg_kwargs:
      absdelta: 1.e-6
      maxiter: 2000
  nonlinearly_update_kwargs:
    minimize_kwargs:
      name: "nonlin sampling"
      xtol: 2.e-4
      cg_kwargs:
        name: null
      maxiter: 25
  kl_kwargs:
    minimize_kwargs:
      name: "M"
      absdelta: 1.e-12
      maxiter: 15
      cg_kwargs:
        name: "MCG"
  sample_mode: 'nonlinear_resample'
